fun testThrow() {
    try { throw(36); } catch (exitCode) {}
}
